<?xml version="1.0" encoding="utf-8"?><Database Name="ABC" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ABC;Integrated Security=True" SettingsObjectName="DataInterFace.Properties.Settings" SettingsPropertyName="ABCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LD_field" Member="LD_field">
    <Type Name="LD_field">
      <Column Name="field" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[index]" Member="index" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
</Database>